name: diffmet-py311
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pytorch-gpu=2.1.2
  - lightning=2.2.1
  - torchmetrics=1.3.1
  - jsonargparse=4.27.5
  - uproot=5.3.1
  - vector=1.3.0
  - matplotlib=3.8.3
  - mplhep=0.3.41
  - scienceplots
  - pdfcombine=1.1.5
  - ipykernel
  - pip
  - pip:
    - tensordict==0.3.1
