min_epochs: 10
max_epochs: 500
accelerator: gpu
devices: 1
log_every_n_steps: 100
enable_progress_bar: false
gradient_clip_val: 0.5
gradient_clip_algorithm: norm
callbacks:
  - class_path: diffmet.lit.callbacks.ResultWriter
  - class_path: diffmet.lit.callbacks.LearningCurvePlotter
  - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
    init_args:
      monitor: val_loss
      mode: min
      patience: 10
