max_epochs: 2
accelerator: gpu
devices: [0]
log_every_n_steps: 1
enable_progress_bar: false
gradient_clip_val: 1
gradient_clip_algorithm: norm
callbacks:
  - class_path: diffmet.lit.callbacks.ResultWriter
  - class_path: diffmet.lit.callbacks.LearningCurvePlotter
