model:
  class_path: diffmet.lit.LitModel
  init_args:
    augmentation:
      class_path: diffmet.data.transforms.Compose
      init_args:
        data_list: []
    preprocessing:
      class_path: diffmet.data.transforms.Compose
      init_args:
        data_list:
        - name: pf_norm
          module: Normalize
          in_keys: [candidates]
          out_keys: [candidates]
          features: [px, py, eta]
          offset: [0.0, 0.0, 0.0]
          scale: [5.729, 5.729, 1.390]
        - name: gen_met_norm
          module: Normalize
          in_keys: [gen_met]
          out_keys: [gen_met]
          features: [px, py]
          offset: [0.0, 0.0]
          scale: [63.891, 63.891]
    model:
      class_path: diffmet.models.Transformer
      init_args:
        embed_dim: 32
        num_heads: 2
        activation: ReLU
        widening_factor: 2
        dropout_p: 0.0
        num_layers: 2
    criterion:
      class_path: torch.nn.MSELoss
data:
  dataset_class_path: diffmet.data.datasets.L1PFDataset
  batch_size: 128
  eval_batch_size: 128
  train_files:
    - /scratch/x2719a04/data/L1METML/perfNano_TTbar_PU200.110X_set0.root
  val_files:
    - /scratch/x2719a04/data/L1METML/perfNano_TTbar_PU200.110X_set4.root
  test_files:
    - /scratch/x2719a04/data/L1METML/perfNano_TTbar_PU200.110X_set5.root
