augmentation:
  class_path: diffmet.data.transforms.Compose
  init_args:
    data_list: []
preprocessing:
  class_path: diffmet.data.transforms.Compose
  init_args:
    data_list:
    - name: track_norm
      module: Normalize
      in_keys: [track]
      out_keys: [track]
      offset: [0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0] # px, py, eta, charge, is_electron, is_muon, is_hadron, is_reco_pu
      scale: [100.0, 100.0, 4.0, 2.0, 1.0, 1.0, 1.0, 1.0]
    - name: tower_norm
      module: Normalize
      in_keys: [tower]
      out_keys: [tower]
      offset: [0.0, 0.0, 0.0, 0.0] # [px, py, eta, is_hadron]
      scale: [200.0, 200.0, 5.0, 1.0]
    - name: gen_met_norm
      module: Normalize
      in_keys: [gen_met]
      out_keys: [gen_met]
      offset: [0.0, 0.0] # [px, py]
      scale: [100.0, 100.0]
model:
  class_path: diffmet.models.DelphesModel
  init_args:
    projection:
      class_path: diffmet.nn.delphes.PFMerger
      init_args:
        track_dim: 8
        tower_dim: 4
        embed_dim: 64
    backbone:
      class_path: diffmet.nn.perceiver.Perceiver
      init_args:
        latent_len: 128
        embed_dim: 64
        num_heads: 8
        dropout_p: 0
        num_layers: 4
        activation: GELU
        widening_factor: 4
    regression_head:
      class_path: torch.nn.Linear
      init_args:
        in_features: 64
        out_features: 2
criterion:
  class_path: torch.nn.MSELoss
